//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bow.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextosValidacionDTO {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextosValidacionDTO() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bow.Resources.TextosValidacionDTO", typeof(TextosValidacionDTO).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el Id del Plan Exequial.
        /// </summary>
        internal static string afiliaciones_convenioRecaudoMasivo_getall_planExequialId_requerido {
            get {
                return ResourceManager.GetString("afiliaciones_convenioRecaudoMasivo_getall_planExequialId_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el Id de la persona encargada del grupo informal.
        /// </summary>
        internal static string afiliaciones_grupoInformal_getall_gruposByContacto_personaId_requerido {
            get {
                return ResourceManager.GetString("afiliaciones_grupoInformal_getall_gruposByContacto_personaId_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el id del grupo informal.
        /// </summary>
        internal static string afiliaciones_grupoInformalEmpleado_getall_grupoId_requerido {
            get {
                return ResourceManager.GetString("afiliaciones_grupoInformalEmpleado_getall_grupoId_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el Id del beneficio del plan exequial.
        /// </summary>
        internal static string beneficiosPlanExequial_delete_Id_requerido {
            get {
                return ResourceManager.GetString("beneficiosPlanExequial_delete_Id_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el Id del beneficio del plan exequial.
        /// </summary>
        internal static string beneficiosPlanExequial_get_id_requerido {
            get {
                return ResourceManager.GetString("beneficiosPlanExequial_get_id_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el Id de la categoría del beneficio.
        /// </summary>
        internal static string beneficiosPlanExequial_getall_categoriaId_requerido {
            get {
                return ResourceManager.GetString("beneficiosPlanExequial_getall_categoriaId_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el Id del plan exequial.
        /// </summary>
        internal static string beneficiosPlanExequial_getall_planExequialId_requerido {
            get {
                return ResourceManager.GetString("beneficiosPlanExequial_getall_planExequialId_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el Id del tipo de beneficio.
        /// </summary>
        internal static string beneficiosPlanExequial_getall_TipoId_requerido {
            get {
                return ResourceManager.GetString("beneficiosPlanExequial_getall_TipoId_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el Id del beneficio del plan exequial.
        /// </summary>
        internal static string beneficiosPlanExequial_puedeEliminar_id_requerido {
            get {
                return ResourceManager.GetString("beneficiosPlanExequial_puedeEliminar_id_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el Id del beneficio.
        /// </summary>
        internal static string beneficiosPlanExequial_save_beneficioId_requerido {
            get {
                return ResourceManager.GetString("beneficiosPlanExequial_save_beneficioId_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el id del beneficio del plan exequial.
        /// </summary>
        internal static string beneficiosPlanExequial_save_beneficioPlanExequialId_requerido {
            get {
                return ResourceManager.GetString("beneficiosPlanExequial_save_beneficioPlanExequialId_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar la cantidad de beneficiarios asignables al beneficio.
        /// </summary>
        internal static string beneficiosPlanExequial_save_cantidadAsignables_requerido {
            get {
                return ResourceManager.GetString("beneficiosPlanExequial_save_cantidadAsignables_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El valor si es asignable o no debe ser &apos;1&apos; si es verdadero o &apos;0&apos; si es falso.
        /// </summary>
        internal static string beneficiosPlanExequial_save_esAsignable_longitud {
            get {
                return ResourceManager.GetString("beneficiosPlanExequial_save_esAsignable_longitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar si el beneficio del plan exequial es asignable o no.
        /// </summary>
        internal static string beneficiosPlanExequial_save_esAsignable_requerido {
            get {
                return ResourceManager.GetString("beneficiosPlanExequial_save_esAsignable_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el Id del estado.
        /// </summary>
        internal static string beneficiosPlanExequial_save_estadoId_requerido {
            get {
                return ResourceManager.GetString("beneficiosPlanExequial_save_estadoId_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el Id del plan exequial.
        /// </summary>
        internal static string beneficiosPlanExequial_save_planExequialId_requerido {
            get {
                return ResourceManager.GetString("beneficiosPlanExequial_save_planExequialId_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el valor del beneficio del plan exequial.
        /// </summary>
        internal static string beneficiosPlanExequial_save_valor_requerido {
            get {
                return ResourceManager.GetString("beneficiosPlanExequial_save_valor_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el Id del plan exequial.
        /// </summary>
        internal static string beneficiosPlanExequial_tipos_planExequialId_requerido {
            get {
                return ResourceManager.GetString("beneficiosPlanExequial_tipos_planExequialId_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el Id del beneficio.
        /// </summary>
        internal static string beneficiosPlanExequial_update_beneficioId_requerido {
            get {
                return ResourceManager.GetString("beneficiosPlanExequial_update_beneficioId_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar la cantidad de beneficiarios asignables al beneficio.
        /// </summary>
        internal static string beneficiosPlanExequial_update_cantidadAsignables_requerido {
            get {
                return ResourceManager.GetString("beneficiosPlanExequial_update_cantidadAsignables_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El valor si es asignable o no debe ser &apos;1&apos; si es verdadero o &apos;0&apos; si es falso.
        /// </summary>
        internal static string beneficiosPlanExequial_update_esAsignable_longitud {
            get {
                return ResourceManager.GetString("beneficiosPlanExequial_update_esAsignable_longitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar si el beneficio del plan exequial es asignable o no.
        /// </summary>
        internal static string beneficiosPlanExequial_update_esAsignable_requerido {
            get {
                return ResourceManager.GetString("beneficiosPlanExequial_update_esAsignable_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el Id del estado.
        /// </summary>
        internal static string beneficiosPlanExequial_update_estadoId_requerido {
            get {
                return ResourceManager.GetString("beneficiosPlanExequial_update_estadoId_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el Id del beneficio del plan exequial.
        /// </summary>
        internal static string beneficiosPlanExequial_update_id_requerido {
            get {
                return ResourceManager.GetString("beneficiosPlanExequial_update_id_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el Id del plan exequial.
        /// </summary>
        internal static string beneficiosPlanExequial_update_planExequialId_requerido {
            get {
                return ResourceManager.GetString("beneficiosPlanExequial_update_planExequialId_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el valor del beneficio del plan exequial.
        /// </summary>
        internal static string beneficiosPlanExequial_update_valor_requerido {
            get {
                return ResourceManager.GetString("beneficiosPlanExequial_update_valor_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el id de la sucursal.
        /// </summary>
        internal static string bowAfiliacionPlanExequial_sucursalId_requerido {
            get {
                return ResourceManager.GetString("bowAfiliacionPlanExequial_sucursalId_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el tipo de plan exequial.
        /// </summary>
        internal static string bowAfiliacionPlanExequial_tipoPlan_requerido {
            get {
                return ResourceManager.GetString("bowAfiliacionPlanExequial_tipoPlan_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el Id de la organización.
        /// </summary>
        internal static string empresasPlanExequial_getall_organizacionId_requerido {
            get {
                return ResourceManager.GetString("empresasPlanExequial_getall_organizacionId_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el Id del plan exequial.
        /// </summary>
        internal static string empresasPlanExequial_getall_planExequialId_requerido {
            get {
                return ResourceManager.GetString("empresasPlanExequial_getall_planExequialId_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el Id del grupo familiar.
        /// </summary>
        internal static string grupoFamiliar_delete_id_requerido {
            get {
                return ResourceManager.GetString("grupoFamiliar_delete_id_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el Id del grupo familiar.
        /// </summary>
        internal static string grupoFamiliar_get_id_requerido {
            get {
                return ResourceManager.GetString("grupoFamiliar_get_id_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el Id del plan exequial.
        /// </summary>
        internal static string grupoFamiliar_getAll_planExequialId_requerido {
            get {
                return ResourceManager.GetString("grupoFamiliar_getAll_planExequialId_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el Id del grupo familiar.
        /// </summary>
        internal static string grupoFamiliar_puedeEliminar_id_requerido {
            get {
                return ResourceManager.GetString("grupoFamiliar_puedeEliminar_id_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La longitud de la descripción no puede ser superior a 200 caracteres.
        /// </summary>
        internal static string grupoFamiliar_save_descripcion_longitud {
            get {
                return ResourceManager.GetString("grupoFamiliar_save_descripcion_longitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar la descripción del grupo familiar.
        /// </summary>
        internal static string grupoFamiliar_save_descripcion_requerido {
            get {
                return ResourceManager.GetString("grupoFamiliar_save_descripcion_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el Id del estado.
        /// </summary>
        internal static string grupoFamiliar_save_estadoId_requerido {
            get {
                return ResourceManager.GetString("grupoFamiliar_save_estadoId_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el id del grupo familiar.
        /// </summary>
        internal static string grupoFamiliar_save_id_requerido {
            get {
                return ResourceManager.GetString("grupoFamiliar_save_id_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La longitud del nombre no puede ser superior a 50 caracteres.
        /// </summary>
        internal static string grupoFamiliar_save_nombre_longitud {
            get {
                return ResourceManager.GetString("grupoFamiliar_save_nombre_longitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el nombre del grupo familiar.
        /// </summary>
        internal static string grupoFamiliar_save_nombre_requerido {
            get {
                return ResourceManager.GetString("grupoFamiliar_save_nombre_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permitir afiliados adicionales debe ser de 1 caracter.
        /// </summary>
        internal static string grupoFamiliar_save_permitirAfiliadosAdicionales_longitud {
            get {
                return ResourceManager.GetString("grupoFamiliar_save_permitirAfiliadosAdicionales_longitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar si permite afiliados adicionales en el grupo familiar.
        /// </summary>
        internal static string grupoFamiliar_save_permitirAfiliadosAdicionales_requerido {
            get {
                return ResourceManager.GetString("grupoFamiliar_save_permitirAfiliadosAdicionales_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el Id del plan exequial.
        /// </summary>
        internal static string grupoFamiliar_save_planExequialId_requerido {
            get {
                return ResourceManager.GetString("grupoFamiliar_save_planExequialId_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiene cuota inicial debe ser de 1 caracter.
        /// </summary>
        internal static string grupoFamiliar_save_tieneCuotaInicial_longitud {
            get {
                return ResourceManager.GetString("grupoFamiliar_save_tieneCuotaInicial_longitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar si tiene cuota inicial el grupo familiar.
        /// </summary>
        internal static string grupoFamiliar_save_tieneCuotaInicial_requerido {
            get {
                return ResourceManager.GetString("grupoFamiliar_save_tieneCuotaInicial_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el valor base del grupo familiar.
        /// </summary>
        internal static string grupoFamiliar_save_valorBase_requerido {
            get {
                return ResourceManager.GetString("grupoFamiliar_save_valorBase_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el valor inicial del grupo familiar.
        /// </summary>
        internal static string grupoFamiliar_save_valorInicial_requerido {
            get {
                return ResourceManager.GetString("grupoFamiliar_save_valorInicial_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el Id del grupo familiar.
        /// </summary>
        internal static string grupoFamiliarParentesco_get_grupoFamiliarId_requerido {
            get {
                return ResourceManager.GetString("grupoFamiliarParentesco_get_grupoFamiliarId_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el Id del plan exequial.
        /// </summary>
        internal static string grupoFamiliarParentesco_get_parentescoId_requerido {
            get {
                return ResourceManager.GetString("grupoFamiliarParentesco_get_parentescoId_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el Id del grupo familiar.
        /// </summary>
        internal static string grupoFamiliarParentesco_save_grupoFamiliarId_requerido {
            get {
                return ResourceManager.GetString("grupoFamiliarParentesco_save_grupoFamiliarId_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el Id del parentesco.
        /// </summary>
        internal static string grupoFamiliarParentesco_save_parentescoId_requerido {
            get {
                return ResourceManager.GetString("grupoFamiliarParentesco_save_parentescoId_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validar solo ingreso debe ser de 1 caracter.
        /// </summary>
        internal static string grupoFamiliarParentesco_save_validarSoloIngreso_longitud {
            get {
                return ResourceManager.GetString("grupoFamiliarParentesco_save_validarSoloIngreso_longitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar si el parentesco solo se valida al ingreso.
        /// </summary>
        internal static string grupoFamiliarParentesco_save_validarSoloIngreso_requerido {
            get {
                return ResourceManager.GetString("grupoFamiliarParentesco_save_validarSoloIngreso_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el Id del grupo familiar.
        /// </summary>
        internal static string parentescos_getall_grupoFamiliarId_requerido {
            get {
                return ResourceManager.GetString("parentescos_getall_grupoFamiliarId_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el Id del plan exequial.
        /// </summary>
        internal static string parentescos_getall_planExequialId_requerido {
            get {
                return ResourceManager.GetString("parentescos_getall_planExequialId_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La longitud del primer apellido no puede ser superior a 50 caracteres, por favor verifique.
        /// </summary>
        internal static string persona_apellido1_max_longitud {
            get {
                return ResourceManager.GetString("persona_apellido1_max_longitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el primer apellido de la persona.
        /// </summary>
        internal static string persona_apellido1_requerido {
            get {
                return ResourceManager.GetString("persona_apellido1_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La longitud del segundo apellido no puede ser superior a 50 caracteres, por favor verifique.
        /// </summary>
        internal static string persona_apellido2_max_longitud {
            get {
                return ResourceManager.GetString("persona_apellido2_max_longitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El correo electrónico es inválido.
        /// </summary>
        internal static string persona_correo_electronico_invalido {
            get {
                return ResourceManager.GetString("persona_correo_electronico_invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La longitud del correo electrónico no puede ser superiror a 80 caracteres, por favor verifique.
        /// </summary>
        internal static string persona_correo_electronico_max_longitud {
            get {
                return ResourceManager.GetString("persona_correo_electronico_max_longitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el estado civil de la persona.
        /// </summary>
        internal static string persona_estadocivil_requerido {
            get {
                return ResourceManager.GetString("persona_estadocivil_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar la fecha de nacimiento.
        /// </summary>
        internal static string persona_fecha_nacimiento_requerido {
            get {
                return ResourceManager.GetString("persona_fecha_nacimiento_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar la nacionalidad de la persona.
        /// </summary>
        internal static string persona_nacionalidad_requerido {
            get {
                return ResourceManager.GetString("persona_nacionalidad_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La longitud del nombre no puede ser superior a 50 caracteres, por favor verifique.
        /// </summary>
        internal static string persona_nombre_max_longitud {
            get {
                return ResourceManager.GetString("persona_nombre_max_longitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe Indicar el nombre de la Persona.
        /// </summary>
        internal static string persona_nombre_requerido {
            get {
                return ResourceManager.GetString("persona_nombre_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el número de documento.
        /// </summary>
        internal static string persona_numero_documento_requerido {
            get {
                return ResourceManager.GetString("persona_numero_documento_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar la profesión de la persona.
        /// </summary>
        internal static string persona_profesion_requerido {
            get {
                return ResourceManager.GetString("persona_profesion_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar si la persona tiene o no documento de identificación.
        /// </summary>
        internal static string persona_tiene_documento_requerido {
            get {
                return ResourceManager.GetString("persona_tiene_documento_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar si la persona tiene o no fecha de nacimiento.
        /// </summary>
        internal static string persona_tiene_fechanacimiento_requerido {
            get {
                return ResourceManager.GetString("persona_tiene_fechanacimiento_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el documento de identificación de la persona.
        /// </summary>
        internal static string persona_tipo_documento_requerido {
            get {
                return ResourceManager.GetString("persona_tipo_documento_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar la nacionalidad de la persona.
        /// </summary>
        internal static string personas_nuevapersona_paisRequerido {
            get {
                return ResourceManager.GetString("personas_nuevapersona_paisRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el estado del plan exequial.
        /// </summary>
        internal static string planExequial_cambiarEstado_estado_requerido {
            get {
                return ResourceManager.GetString("planExequial_cambiarEstado_estado_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el Id del plan exequial.
        /// </summary>
        internal static string planExequial_cambiarEstado_id_requerido {
            get {
                return ResourceManager.GetString("planExequial_cambiarEstado_id_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el Id del plan exequial.
        /// </summary>
        internal static string planExequial_delete_id_requerido {
            get {
                return ResourceManager.GetString("planExequial_delete_id_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el Id del plan exequial.
        /// </summary>
        internal static string planExequial_get_id_requerido {
            get {
                return ResourceManager.GetString("planExequial_get_id_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el Id del plan exequial.
        /// </summary>
        internal static string planExequial_puedeEliminar_id_requerido {
            get {
                return ResourceManager.GetString("planExequial_puedeEliminar_id_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La longitud del nombre no puede ser superior a 300 caracteres.
        /// </summary>
        internal static string planExequial_save_descripcion_longitud {
            get {
                return ResourceManager.GetString("planExequial_save_descripcion_longitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar la descripción del plan exequial.
        /// </summary>
        internal static string planExequial_save_descripcion_requerido {
            get {
                return ResourceManager.GetString("planExequial_save_descripcion_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el Id del estado.
        /// </summary>
        internal static string planExequial_save_estadoId_requerido {
            get {
                return ResourceManager.GetString("planExequial_save_estadoId_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el id del plan exequial.
        /// </summary>
        internal static string planExequial_save_id_requerido {
            get {
                return ResourceManager.GetString("planExequial_save_id_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el Id de la moneda.
        /// </summary>
        internal static string planExequial_save_monedaId_requerido {
            get {
                return ResourceManager.GetString("planExequial_save_monedaId_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La longitud del nombre no puede ser superior a 150 caracteres.
        /// </summary>
        internal static string planExequial_save_nombre_longitud {
            get {
                return ResourceManager.GetString("planExequial_save_nombre_longitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el nombre del plan exequial.
        /// </summary>
        internal static string planExequial_save_nombre_requerido {
            get {
                return ResourceManager.GetString("planExequial_save_nombre_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar si el plan exequial aplica para empresa.
        /// </summary>
        internal static string planExequial_save_planEmpresarial_requerido {
            get {
                return ResourceManager.GetString("planExequial_save_planEmpresarial_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar si el plan exequial aplica para familia.
        /// </summary>
        internal static string planExequial_save_planFamiliar_requerido {
            get {
                return ResourceManager.GetString("planExequial_save_planFamiliar_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar si el plan exequial aplica para grupo.
        /// </summary>
        internal static string planExequial_save_planGrupo_requerido {
            get {
                return ResourceManager.GetString("planExequial_save_planGrupo_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el Id del plan exequial.
        /// </summary>
        internal static string planExequialMoneda_get_id_requerido {
            get {
                return ResourceManager.GetString("planExequialMoneda_get_id_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el Id del recaudo masivo plan exequial.
        /// </summary>
        internal static string planExequialRecaudoMasivo_delete_Id_requerido {
            get {
                return ResourceManager.GetString("planExequialRecaudoMasivo_delete_Id_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el Id del plan exequial.
        /// </summary>
        internal static string planExequialRecaudoMasivo_getall_planExequialId_requerido {
            get {
                return ResourceManager.GetString("planExequialRecaudoMasivo_getall_planExequialId_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el id del recaudo masivo del plan exequial.
        /// </summary>
        internal static string planExequialRecaudoMasivo_puedeEliminar_id_requerido {
            get {
                return ResourceManager.GetString("planExequialRecaudoMasivo_puedeEliminar_id_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar si el recaudo es obligatorio o no.
        /// </summary>
        internal static string planExequialRecaudoMasivo_save_esObligatorio_requerido {
            get {
                return ResourceManager.GetString("planExequialRecaudoMasivo_save_esObligatorio_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el Id del plan exequial.
        /// </summary>
        internal static string planExequialRecaudoMasivo_save_planExequialId_requerido {
            get {
                return ResourceManager.GetString("planExequialRecaudoMasivo_save_planExequialId_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el Id del recaudo masivo.
        /// </summary>
        internal static string planExequialRecaudoMasivo_save_recaudoMasivoId_requerido {
            get {
                return ResourceManager.GetString("planExequialRecaudoMasivo_save_recaudoMasivoId_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar si el recaudo masivo es obligatorio o no.
        /// </summary>
        internal static string planExequialRecaudoMasivo_update_esObligatorio_requerido {
            get {
                return ResourceManager.GetString("planExequialRecaudoMasivo_update_esObligatorio_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el Id del convenio de recaudo del plan exequial.
        /// </summary>
        internal static string planExequialRecaudoMasivo_update_id_requerido {
            get {
                return ResourceManager.GetString("planExequialRecaudoMasivo_update_id_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el Id del plan exequial.
        /// </summary>
        internal static string planExequialRecaudoMasivo_update_planExequialId_requerido {
            get {
                return ResourceManager.GetString("planExequialRecaudoMasivo_update_planExequialId_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el Id de recaudo masivo.
        /// </summary>
        internal static string planExequialRecaudoMasivo_update_recaudoMasivoId_requerido {
            get {
                return ResourceManager.GetString("planExequialRecaudoMasivo_update_recaudoMasivoId_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el Id del rango del parentesco.
        /// </summary>
        internal static string rangoParentesco_delete_id_requerido {
            get {
                return ResourceManager.GetString("rangoParentesco_delete_id_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el Id del rango del parentesco.
        /// </summary>
        internal static string rangoParentesco_get_id_requerido {
            get {
                return ResourceManager.GetString("rangoParentesco_get_id_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el Id del rango del parentesco.
        /// </summary>
        internal static string rangoParentesco_puedeEliminar_id_requerido {
            get {
                return ResourceManager.GetString("rangoParentesco_puedeEliminar_id_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar la edad máxima del rango del parentesco.
        /// </summary>
        internal static string rangoParentesco_save_edadMaxima_requerido {
            get {
                return ResourceManager.GetString("rangoParentesco_save_edadMaxima_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar la edad mínima del rango del parentesco.
        /// </summary>
        internal static string rangoParentesco_save_edadMinima_requerido {
            get {
                return ResourceManager.GetString("rangoParentesco_save_edadMinima_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el Id grupo parentesco.
        /// </summary>
        internal static string rangoParentesco_save_grupoParentescoId_requerido {
            get {
                return ResourceManager.GetString("rangoParentesco_save_grupoParentescoId_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el Id del rango del parentesco.
        /// </summary>
        internal static string rangoParentesco_save_id_requerido {
            get {
                return ResourceManager.GetString("rangoParentesco_save_id_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el periodo de carencia del rango del parentesco.
        /// </summary>
        internal static string rangoParentesco_save_periodoCarencia_requerido {
            get {
                return ResourceManager.GetString("rangoParentesco_save_periodoCarencia_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tipo de valor adicional debe ser de 1 caracter.
        /// </summary>
        internal static string rangoParentesco_save_tipoValorAdicional_longitud {
            get {
                return ResourceManager.GetString("rangoParentesco_save_tipoValorAdicional_longitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el tipo de valor adicional del rango del parentesco.
        /// </summary>
        internal static string rangoParentesco_save_tipoValorAdicional_requerido {
            get {
                return ResourceManager.GetString("rangoParentesco_save_tipoValorAdicional_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tipo de valor básico debe ser de 1 caracter.
        /// </summary>
        internal static string rangoParentesco_save_tipoValorBasico_longitud {
            get {
                return ResourceManager.GetString("rangoParentesco_save_tipoValorBasico_longitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el tipo de valor básico del rango del parentesco.
        /// </summary>
        internal static string rangoParentesco_save_tipoValorBasico_requerido {
            get {
                return ResourceManager.GetString("rangoParentesco_save_tipoValorBasico_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La unidad del periodo de carencia debe ser de 1 caracter.
        /// </summary>
        internal static string rangoParentesco_save_unidadPeriodoCarencia_longitud {
            get {
                return ResourceManager.GetString("rangoParentesco_save_unidadPeriodoCarencia_longitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar la unidad del periodo de carencia del rango del parentesco.
        /// </summary>
        internal static string rangoParentesco_save_unidadPeriodoCarencia_requerido {
            get {
                return ResourceManager.GetString("rangoParentesco_save_unidadPeriodoCarencia_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el valor adicional del rango del parentesco.
        /// </summary>
        internal static string rangoParentesco_save_valorAdicional_requerido {
            get {
                return ResourceManager.GetString("rangoParentesco_save_valorAdicional_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el valor básico del rango del parentesco.
        /// </summary>
        internal static string rangoParentesco_save_valorBasico_requerido {
            get {
                return ResourceManager.GetString("rangoParentesco_save_valorBasico_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el Id del grupo familiar.
        /// </summary>
        internal static string rangosParentescos_getall_grupoFamiliarId_requerido {
            get {
                return ResourceManager.GetString("rangosParentescos_getall_grupoFamiliarId_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el Id del plan exequial.
        /// </summary>
        internal static string rangosParentescos_getall_planExequialId_requerido {
            get {
                return ResourceManager.GetString("rangosParentescos_getall_planExequialId_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el Id de la empresa-organización.
        /// </summary>
        internal static string sucursalesPlanExequial_getall_empresaOrganizacionId_requerido {
            get {
                return ResourceManager.GetString("sucursalesPlanExequial_getall_empresaOrganizacionId_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el Id del plan exequial.
        /// </summary>
        internal static string sucursalesPlanExequial_getall_planExequialId_requerido {
            get {
                return ResourceManager.GetString("sucursalesPlanExequial_getall_planExequialId_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar si la sucursal se asigna al plan o no.
        /// </summary>
        internal static string sucursalPlanExequial_update_asignadoAlPlan_requerido {
            get {
                return ResourceManager.GetString("sucursalPlanExequial_update_asignadoAlPlan_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el Id del plan exequial.
        /// </summary>
        internal static string sucursalPlanExequial_update_planExequialId_requerido {
            get {
                return ResourceManager.GetString("sucursalPlanExequial_update_planExequialId_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el Id de la sucursal.
        /// </summary>
        internal static string sucursalPlanExequial_update_sucursald_requerido {
            get {
                return ResourceManager.GetString("sucursalPlanExequial_update_sucursald_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el barrio de la dirección.
        /// </summary>
        internal static string zonificacion_savedireccionconnomenclatura_barrio_requerido {
            get {
                return ResourceManager.GetString("zonificacion_savedireccionconnomenclatura_barrio_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La longitud del portón de la dirección no puede ser superior a 20 caracteres.
        /// </summary>
        internal static string zonificacion_savedireccionconnomenclatura_porton_max_longitud {
            get {
                return ResourceManager.GetString("zonificacion_savedireccionconnomenclatura_porton_max_longitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el portón de la dirección.
        /// </summary>
        internal static string zonificacion_savedireccionconnomenclatura_porton_requerido {
            get {
                return ResourceManager.GetString("zonificacion_savedireccionconnomenclatura_porton_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar la vía principal de la dirección.
        /// </summary>
        internal static string zonificacion_savedireccionconnomenclatura_viaprincipal_requerido {
            get {
                return ResourceManager.GetString("zonificacion_savedireccionconnomenclatura_viaprincipal_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar la vía secundaría de la dirección.
        /// </summary>
        internal static string zonificacion_savedireccionconnomenclatura_viasecundaria_requerido {
            get {
                return ResourceManager.GetString("zonificacion_savedireccionconnomenclatura_viasecundaria_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el nombre de la vía.
        /// </summary>
        internal static string zonificacion_savedireccionconnomenclaturausa_nombrevia_requerido {
            get {
                return ResourceManager.GetString("zonificacion_savedireccionconnomenclaturausa_nombrevia_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el número de la dirección.
        /// </summary>
        internal static string zonificacion_savedireccionconnomenclaturausa_numero_requerido {
            get {
                return ResourceManager.GetString("zonificacion_savedireccionconnomenclaturausa_numero_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La longitud del número de la dirección no puede ser superior a 20 caracteres.
        /// </summary>
        internal static string zonificacion_savedireccionconnomenclaturausa_porton_max_longitud {
            get {
                return ResourceManager.GetString("zonificacion_savedireccionconnomenclaturausa_porton_max_longitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el tipo de vía de la dirección.
        /// </summary>
        internal static string zonificacion_savedireccionconnomenclaturausa_tipovia_requerido {
            get {
                return ResourceManager.GetString("zonificacion_savedireccionconnomenclaturausa_tipovia_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el ZipCode de la dirección.
        /// </summary>
        internal static string zonificacion_savedireccionconnomenclaturausa_zipcode_requerido {
            get {
                return ResourceManager.GetString("zonificacion_savedireccionconnomenclaturausa_zipcode_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el barrio de la dirección.
        /// </summary>
        internal static string zonificacion_savedireccionsinnomenclatura_barrio_requerido {
            get {
                return ResourceManager.GetString("zonificacion_savedireccionsinnomenclatura_barrio_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La longitud del nombre de la dirección no puede ser superior a 150 caracteres.
        /// </summary>
        internal static string zonificacion_savedireccionsinnomenclatura_nombre_max_longitud {
            get {
                return ResourceManager.GetString("zonificacion_savedireccionsinnomenclatura_nombre_max_longitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el nombre de la dirección.
        /// </summary>
        internal static string zonificacion_savedireccionsinnomenclatura_nombre_requerido {
            get {
                return ResourceManager.GetString("zonificacion_savedireccionsinnomenclatura_nombre_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La longitud de la pista de la dirección no puede ser superior a 300 caracteres.
        /// </summary>
        internal static string zonificacion_savedireccionsinnomenclatura_pista_max_longitud {
            get {
                return ResourceManager.GetString("zonificacion_savedireccionsinnomenclatura_pista_max_longitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La longitud del nombre de la dirección no puede ser superior a 150 caracteres.
        /// </summary>
        internal static string zonificacion_savedireccionsinnomenclaturausa_nombre_max_longitud {
            get {
                return ResourceManager.GetString("zonificacion_savedireccionsinnomenclaturausa_nombre_max_longitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el nombre de la dirección.
        /// </summary>
        internal static string zonificacion_savedireccionsinnomenclaturausa_nombre_requerido {
            get {
                return ResourceManager.GetString("zonificacion_savedireccionsinnomenclaturausa_nombre_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar el ZipCode de la dirección.
        /// </summary>
        internal static string zonificacion_savedireccionsinnomenclaturausa_zipcode_requerido {
            get {
                return ResourceManager.GetString("zonificacion_savedireccionsinnomenclaturausa_zipcode_requerido", resourceCulture);
            }
        }
    }
}
