// <auto-generated />
namespace Bow.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class migracion_marzo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migracion_marzo));
        
        string IMigrationMetadata.Id
        {
            get { return "201504061947490_migracion_marzo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
